services:  
  iris:
    build: .
    ports:
      - 5073:52773
      - 5072:1972
      - 5001:5001
    volumes:
      - .:/home/irisowner/irislab
    environment:
      - PIP_BREAK_SYSTEM_PACKAGES=1
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/irisowner/bin:/home/irisowner/.local/bin
    command:
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
